---
deployment:
  tasks:
    - export DEPLOYPATH=/home/example/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R core $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH